name: Build CLI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: macos-11
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17' 

      - run: |
          git clone https://github.com/osmosis-labs/osmosis.git
          cd osmosis
          make build
          ls -la build



  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.17' 

      - name: build script
        run: go install

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: builddir/release-builds
          key: release-builds

      - name: run script
        run: mkdir -p builddir && cd builddir && cosmos-cli-builder
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: ./builddir/release-builds/*
