name: Build CLI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    concurrency: build-${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.17' 

      - name: build script
        run: go install

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: builddir/release-builds
          key: release-builds-${{ matrix.os }}-3 #Change whenever invalidation is needed

      - name: run script
        run: mkdir -p builddir && cd builddir && cosmos-cli-builder
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest-${{ matrix.os }}
          prerelease: false
          title: "Latest release for ${{ matrix.os }}"
          files: ./builddir/release-builds/*
